{
    "name": "VPK Procurement Auto PR - แผนจัดซื้อและสร้าง PR อัตโนมัติ",
    "version": "18.0.1.34.0",
    "category": "Purchases",
    "summary": "แผนจัดซื้อจัดจ้างประจำปี + Auto Gen PR จากจุดสั่งซื้อและสัญญาใกล้หมดอายุ",
    "depends": [
        "purchase_request",
        "stock",
        "purchase",
        "account",
        "purchase_reception_status",
        "purchase_cancel_reason",
        "vpk_purchase_contract",
        "vpk_purchase_portal_egp",
        "vpk_budget",
    ],
    "data": [
        "security/credit_note_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "data/purchase_cancel_reason_data.xml",
        "data/vendor_group_data.xml",
        "views/procurement_annual_plan_views.xml",
        "views/procurement_plan_amendment_views.xml",
        "views/purchase_request_naming_views.xml",
        "views/procurement_classification_views.xml",
        "views/purchase_cancellation_views.xml",
        "views/purchase_penalty_views.xml",
        "views/purchase_guarantee_views.xml",
        "views/vendor_bill_duplicate_views.xml",
        "views/credit_note_security_views.xml",
        "views/purchase_auto_close_views.xml",
        "views/pending_receipt_report_views.xml",
        "views/daily_receipt_report_views.xml",
        "views/vendor_product_price_report_views.xml",
        "views/purchase_comparison_report_views.xml",
        "views/purchase_material_equipment_report_views.xml",
        "views/vendor_group_report_views.xml",
        "views/purchase_drug_list_report_views.xml",
        "views/procurement_registry_report_views.xml",
        "views/due_delivery_report_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
