# Copyright 2026 VPK
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0).

{
    "name": "VPK Official Document - หนังสือราชการ",
    "version": "18.0.1.16.0",
    "category": "Purchases",
    "summary": "ออกหนังสือราชการจากแบบฟอร์ม Word เช่น คำสั่งแต่งตั้งคณะกรรมการตรวจรับ และบันทึกขออนุมัติแต่งตั้งคณะกรรมการกำหนดคุณลักษณะ",
    "author": "VPK",
    "license": "LGPL-3",
    "depends": [
        "purchase_request",
        "l10n_th_gov_purchase_request",
        "l10n_th_base_utils",
        "purchase_work_acceptance",
        "vpk_work_acceptance",
        "vpk_pr_saraban",
        "mail",
        "hr",
        "base_tier_validation",
        "base_tier_validation_formula",
        "purchase_request_tier_validation",
    ],
    "external_dependencies": {"python": ["docx", "pypdfium2", "PIL"]},
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/official_document_template_data.xml",
        "data/ir_config_parameter.xml",
        "data/tier_definition_data.xml",
        "views/official_document_views.xml",
        "views/official_document_template_views.xml",
        "views/purchase_request_views.xml",
        "views/saraban_document_views.xml",
        "views/work_acceptance_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
        "report/official_document_report.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "vpk_official_document/static/src/scss/official_order_report.scss",
        ],
        "web.assets_backend": [
            "vpk_official_document/static/src/js/sign_pdf_viewer_dialog.js",
            "vpk_official_document/static/src/xml/sign_pdf_viewer_dialog.xml",
            "vpk_official_document/static/src/scss/sign_pdf_viewer_dialog.scss",
            "vpk_official_document/static/src/js/sign_pdf_viewer_action.js",
            "vpk_official_document/static/src/js/official_document_form.js",
            "vpk_official_document/static/src/js/attachment_cards_field.js",
            "vpk_official_document/static/src/xml/attachment_cards_field.xml",
            "vpk_official_document/static/src/scss/attachment_cards_field.scss",
            "vpk_official_document/static/src/js/pdf_icon_field.js",
            "vpk_official_document/static/src/xml/pdf_icon_field.xml",
            "vpk_official_document/static/src/scss/pdf_icon_field.scss",
        ],
    },
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
