[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_template = template1
list_db = True
http_port = 8069
proxy_mode = False
workers = 0
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
data_dir = /var/lib/odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/extra-addons/account-financial-tools-18.0,/mnt/extra-addons/base_accounting_kit-18.0.5.0.9,/mnt/extra-addons/l10n-thailand-18.0,/mnt/extra-addons/purchase-workflow-18.0,/mnt/extra-addons/reporting-engine-18.0,/mnt/extra-addons/server-ux-18.0,/mnt/extra-addons/partner-contact-18.0,/mnt/extra-addons/hr-expense-18.0,/mnt/extra-addons/server-tools-18.0,/mnt/extra-addons/account-invoicing-18.0,/mnt/extra-addons/account-payment-18.0,/mnt/extra-addons/stock-logistics-workflow-18.0
without_demo = False
