{
    "name": "VPK Budget",
    "version": "18.0.2.80.0",
    "category": "Accounting",
    "summary": "งบประมาณ แหล่งเงิน กลุ่มงบประมาณ คำของบ และบัญชีวิเคราะห์",
    "author": "VPK",
    "external_dependencies": {"python": ["xlsxwriter", "openpyxl"]},
    "depends": [
        "base_account_budget",
        "analytic",
        "mail",
        "account",
        "product",
        "uom",
        "purchase_request_department",
        "purchase_request_tier_validation",
    ],
    "data": [
        "security/vpk_budget_security.xml",
        "security/ir.model.access.csv",
        "data/budget_fund_source_data.xml",
        "data/budget_group_data.xml",
        "data/budget_type_data.xml",
        "data/budget_asset_type_data.xml",
        "data/budget_asset_category_data.xml",
        "data/budget_request_form_type_data.xml",
        "data/budget_request_form_type_line_data.xml",
        "security/budget_request_form_type_access.xml",
        "security/budget_material_sub_type_access.xml",
        "security/budget_material_detail_access.xml",
        "security/budget_asset_type_access.xml",
        "security/budget_asset_category_access.xml",
        "security/budget_summary_wizard_access.xml",
        "security/budget_master_import_wizard_access.xml",
        "data/departmental_budget_request_sequence.xml",
        "views/budget_fund_source_views.xml",
        "views/budget_group_views.xml",
        "views/budget_type_views.xml",
        "views/budget_material_sub_type_views.xml",
        "views/budget_asset_category_views.xml",
        "views/budget_request_form_type_views.xml",
        "views/menu.xml",
        "views/budget_accounting_menus.xml",
        "views/account_budget_views.xml",
        "views/purchase_request_budget_views.xml",
        "views/purchase_order_budget_views.xml",
        "views/account_move_budget_views.xml",
        "report/departmental_budget_request_material_report.xml",
        "views/departmental_budget_request_views.xml",
        "data/budget_request_form_type_menu_sync.xml",
        "views/departmental_budget_summary_wizard_views.xml",
        "wizard/budget_master_import_wizard_views.xml",
    ],
    "installable": True,
    "application": True,
    "assets": {
        "web.assets_backend": [
            "vpk_budget/static/src/scss/budget_form.scss",
            "vpk_budget/static/src/scss/departmental_budget_request_form.scss",
            "vpk_budget/static/src/scss/budget_dashboard.scss",
            "vpk_budget/static/src/scss/budget_overview_dashboard.scss",
            "vpk_budget/static/src/scss/budget_department_dashboard.scss",
            "vpk_budget/static/src/js/material_detail_usage_qty_headers.js",
            "vpk_budget/static/src/dashboard/budget_dashboard.js",
            "vpk_budget/static/src/dashboard/budget_dashboard.xml",
            "vpk_budget/static/src/dashboard/budget_overview_dashboard.js",
            "vpk_budget/static/src/dashboard/budget_overview_dashboard.xml",
            "vpk_budget/static/src/dashboard/budget_department_dashboard.js",
            "vpk_budget/static/src/dashboard/budget_department_dashboard.xml",
        ],
    },
}
