{
    "name": "VPK Stock Warehouse Overview",
    "version": "18.0.1.6.0",
    "category": "Inventory",
    "summary": "Warehouse and bin/location explorer with panel navigation",
    "author": "VPK",
    "license": "LGPL-3",
    "depends": ["stock"],
    "data": [
        "data/central_transfer_flow.xml",
        "views/stock_location_overview_views.xml",
        "views/vendor_receipt_schedule_views.xml",
        "views/central_transfer_flow_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "vpk_stock_warehouse/static/src/scss/warehouse_overview.scss",
            "vpk_stock_warehouse/static/src/scss/operations_dashboard.scss",
            "vpk_stock_warehouse/static/src/scss/inventory_status_dashboard.scss",
            "vpk_stock_warehouse/static/src/dashboard/warehouse_overview.js",
            "vpk_stock_warehouse/static/src/dashboard/warehouse_overview.xml",
            "vpk_stock_warehouse/static/src/dashboard/operations_dashboard.js",
            "vpk_stock_warehouse/static/src/dashboard/operations_dashboard.xml",
            "vpk_stock_warehouse/static/src/dashboard/inventory_status_dashboard.js",
            "vpk_stock_warehouse/static/src/dashboard/inventory_status_dashboard.xml",
        ],
    },
    "installable": True,
    "application": False,
}
