{
    "name": "Hospital Budget Customization",
    "version": "15.0.1.0.0",
    "summary": "Hospital budget planning, control, and approval enhancements.",
    "category": "Accounting",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": [
        "web",
        "purchase",
        "purchase_request_budget",
        "purchase_budget_commitment",
        "base_account_budget",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/budget_fund_source_data.xml",
        "views/budget_fund_source_views.xml",
        "views/budget_material_type_views.xml",
        "views/budget_line_adjustment_wizard_views.xml",
        "views/budget_comparison_report_wizard_views.xml",
        "views/account_budget_views.xml",
        "views/res_company_views.xml",
        "views/purchase_request_views.xml",
        "views/purchase_order_views.xml",
        "report/purchase_request_memo_report.xml",
        "report/budget_comparison_report_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hospital_budget_customization/static/src/js/tinymce_html_field.js",
        ],
    },
    "installable": True,
    "application": False,
}
